spring:
  application:
    name: batch-demo
 
  batch:    jdbc:      initialize-schema: always
      
  datasource:    url: jdbc:h2:file:C:/dev/data/batchdb
    driver-class-name: org.h2.Driver
#    username:
    hikari:
      connection-timeout: 2000 
      maximum-pool-size: 10
      pool-name: my-pool
    
  jpa:    database-platform: org.hibernate.dialect.H2Dialect      

    
